---
- name: Pull NGINX Docker image
  community.docker.docker_image:
    name: nginx
    source: pull
  # environment:
  #   DOCKER_HOST: unix://{{ lookup('env', 'HOME') }}/.docker/run/docker.sock
  tags: pull

- name: Start NGINX container
  community.docker.docker_container:
    name: nginx_server
    image: nginx
    state: started
    restart_policy: always
    published_ports:
      - "8080:80"
  # environment:
  #   DOCKER_HOST: unix://{{ lookup('env', 'HOME') }}/.docker/run/docker.sock
  tags: start

- name: Stop NGINX container
  community.docker.docker_container:
    name: nginx_server
    state: stopped
  # environment:
  #   DOCKER_HOST: unix://{{ lookup('env', 'HOME') }}/.docker/run/docker.sock
  tags: stop

- name: Remove NGINX container
  community.docker.docker_container:
    name: nginx_server
    state: absent
  # environment:
  #   DOCKER_HOST: unix://{{ lookup('env', 'HOME') }}/.docker/run/docker.sock
  tags: remove