---
- name: Ensure Docker is installed on target host
  hosts: web
  become: true
  tasks:
    - name: Check if Docker is already installed
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: docker_check.failed

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_check.failed

    - name: Set up the Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: docker_check.failed

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
      when: docker_check.failed

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: true
      when: docker_check.failed

    - name: Add current user to Docker group (requires re-login)
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      when: docker_check.failed